>>> START RUNNING:  - Train mode:  - Dataset: mnist
Init State dim 6
Init Action dim 4
ROUND:  0
[1, 1]
  0% 0/1000 [00:00<?, ?it/s]Process SpawnPoolWorker-2:
Process SpawnPoolWorker-3:
Process SpawnPoolWorker-6:
Process SpawnPoolWorker-7:
Process SpawnPoolWorker-5:
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  0% 0/1000 [08:13<?, ?it/s]
Traceback (most recent call last):
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/queues.py", line 365, in get
    with self._rlock:
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/synchronize.py", lineTraceback (most recent call last):
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/queues.py", line 365, in get
    with self._rlock:
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/Users/thuydungnguyen/workspace/LAB/DQN-FL/LongND-FL-Parallel-Computing/train.py", line 321, in <module>
    main(args)
  File "/Users/thuydungnguyen/Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/thuydungnguyen/workspace/LAB/DQN-FL/LongND-FL-Parallel-Computing/utils/trainer.py", line 72, in train
    local_inference_loss[id,1] = final_inference_loss
  File "/Users/thuydungnguyen/workspace/LAB/DQN-FL/LongND-FL-Parallel-Computing/utils/trainer.py", line 72, in train
    local_in  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
ference_loss[id,1] = final_inference_loss
  File "_pydevd_bundle/pydevd_cython.pyx", line 1179, in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__
  File "_pydevd_bundle/pydevd_cython.pyx", line 620, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 929, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 920, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 317, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1112, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1127, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/queues.py", line 366, in get
    res = self._reader.recv_bytes()
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
workspace/LAB/DQN-FL/LongND-FL-Parallel-Computing/train.py", line 183, in main
    pool.map(
KeyboardInterrupt
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 762, in wait
    self._event.wait(timeout)
KeyboardInterrupt
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
 95, in __enter__
    return self._semlock.__enter__()
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/thuydungnguyen/workspace/LAB/DQN-FL/LongND-FL-Parallel-Computing/utils/trainer.py", line 72, in train
    local_inference_loss[id,1] = final_inference_loss
  File "/Users/thuydungnguyen/workspace/LAB/DQN-FL/LongND-FL-Parallel-Computing/utils/trainer.py", line 72, in train
    local_inference_loss[id,1] = final_inference_loss
  File "_pydevd_bundle/pydevd_cython.pyx", line 1179, in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__
  File "_pydevd_bundle/pydevd_cython.pyx", line 620, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/queues.py", line 365, in get
    with self._rlock:
  File "/Users/thuydungnguyen/opt/anaconda3/envs/sample-federated/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "_pydevd_bundle/pydevd_cython.pyx", line 929, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 920, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 317, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1112, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1127, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
KeyboardInterrupt
libc++abi: terminating with uncaught exception of type std::__1::system_error: Broken pipe
libc++abi: terminating with uncaught exception of type std::__1::system_error: Broken pipe