2022-03-18 07:28:28,684 INFO    MainThread:28288 [wandb_setup.py:_flush():71] setting env: {}
2022-03-18 07:28:28,685 INFO    MainThread:28288 [wandb_init.py:_log_setup():371] Logging user logs to /mnt/disk1/dungnt-vaipe/federated-learning-dqn/wandb/offline-run-20220318_072828-13rfl9b3/logs/debug.log
2022-03-18 07:28:28,685 INFO    MainThread:28288 [wandb_init.py:_log_setup():372] Logging internal logs to /mnt/disk1/dungnt-vaipe/federated-learning-dqn/wandb/offline-run-20220318_072828-13rfl9b3/logs/debug-internal.log
2022-03-18 07:28:28,685 INFO    MainThread:28288 [wandb_init.py:init():404] calling init triggers
2022-03-18 07:28:28,685 INFO    MainThread:28288 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'num_rounds': 1000, 'num_clients': 10, 'clients_per_round': 10, 'batch_size': 10, 'num_epochs': 5, 'path_data_idx': 'dataset_idx/chexpert/CheXpert-noniid-mnist_equal_sample_1.json', 'learning_rate': 0.01, 'algorithm': '', 'mu': 0.01, 'seed': 10, 'drop_percent': 0.0, 'num_core': 6, 'log_dir': './', 'train_mode': 'benchmark', 'dataset_name': 'chexpert', 'beta': 0.45, 'hidden_dim': 256, 'init_w': 0.001, 'value_lr': 0.001, 'policy_lr': 0.0001, 'max_steps': 800, 'max_frames': 12000, 'batch_size_ddpg': 4, 'gamma': 0.99, 'soft_tau': 0.02, 'path_data_valid_idx': 'dataset_idx/mnist/equal/MNIST-noniid-fedavg_equal_1.json'}
2022-03-18 07:28:28,685 INFO    MainThread:28288 [wandb_init.py:init():460] starting backend
2022-03-18 07:28:28,685 INFO    MainThread:28288 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-18 07:28:28,699 INFO    MainThread:28288 [backend.py:ensure_launched():216] starting backend process...
2022-03-18 07:28:28,712 INFO    MainThread:28288 [backend.py:ensure_launched():221] started backend process with pid: 28344
2022-03-18 07:28:28,714 INFO    MainThread:28288 [wandb_init.py:init():469] backend started and connected
2022-03-18 07:28:28,723 INFO    MainThread:28288 [wandb_init.py:init():533] updated telemetry
2022-03-18 07:28:28,755 INFO    MainThread:28288 [wandb_init.py:init():606] starting run threads in backend
2022-03-18 07:28:31,757 INFO    MainThread:28288 [wandb_run.py:_console_start():1810] atexit reg
2022-03-18 07:28:31,758 INFO    MainThread:28288 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-03-18 07:28:31,759 INFO    MainThread:28288 [wandb_run.py:_redirect():1689] Redirecting console.
2022-03-18 07:28:31,763 INFO    MainThread:28288 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-18 07:28:31,763 INFO    MainThread:28288 [wandb_init.py:init():633] run started, returning control to user process
2022-03-18 07:28:31,766 INFO    MainThread:28288 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-03-18 07:28:31,770 INFO    MainThread:28288 [wandb_run.py:_restore():1752] restore
2022-03-18 07:28:34,774 INFO    MainThread:28288 [wandb_run.py:_wait_for_finish():1912] got exit ret: 
2022-03-18 07:28:34,878 INFO    MainThread:28288 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
local_info {
}

