>>> START RUNNING:  - Train mode:  - Dataset: mnist
Init State dim 6
Init Action dim 4
ROUND:  0
[1, 1]
  0% 0/1000 [00:52<?, ?it/s]
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/thuydungnguyen/workspace/LAB/DQN-FL/LongND-FL-Parallel-Computing/train.py", line 331, in <module>
    main(args)
  File "/Users/thuydungnguyen/workspace/LAB/DQN-FL/LongND-FL-Parallel-Computing/train.py", line 218, in main
    local_loss[i] = local_inference_loss[i, 0]
UnboundLocalError: local variable 'local_loss' referenced before assignment